trigger:
  - master
  - release/*

jobs:
  - job: Windows
    pool:
      vmImage: VS2017-Win2016
    steps:
      - template: azure-pipelines-windows.yml

  - job: Linux
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: azure-pipelines-linux-mac.yml

  - job: macOS
    pool:
      vmImage: macOS 10.13
    steps:
      - template: azure-pipelines-linux-mac.yml
